// <auto-generated />
using KisilerManagement.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace KisilerManagement.Migrations
{
    [DbContext(typeof(KisilerDbContext))]
    partial class KisilerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("KisilerManagement.Models.BilgiTipleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Tanim");

                    b.HasKey("Id");

                    b.ToTable("BilgiTipleri");
                });

            modelBuilder.Entity("KisilerManagement.Models.IletisimBilgileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BilgiIcerigi");

                    b.Property<int>("BilgiTipiID");

                    b.Property<int>("KisiID");

                    b.HasKey("Id");

                    b.HasIndex("BilgiTipiID");

                    b.HasIndex("KisiID");

                    b.ToTable("IletisimBilgileri");
                });

            modelBuilder.Entity("KisilerManagement.Models.Kisiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.Property<string>("Firma");

                    b.Property<string>("Soyad");

                    b.Property<int>("UUID");

                    b.HasKey("Id");

                    b.ToTable("Kisiler");
                });

            modelBuilder.Entity("KisilerManagement.Models.IletisimBilgileri", b =>
                {
                    b.HasOne("KisilerManagement.Models.BilgiTipleri", "BilgiTipi")
                        .WithMany()
                        .HasForeignKey("BilgiTipiID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KisilerManagement.Models.Kisiler", "Kisi")
                        .WithMany()
                        .HasForeignKey("KisiID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
